# Generated by Django 4.0.4 on 2022-06-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=20)),
                ('price', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.cart')),
                ('subTotal', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('shippingCharge', models.CharField(default='100', max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('price', models.CharField(default='0', max_length=100)),
                ('stockCount', models.IntegerField(default='0')),
                ('category', models.ForeignKey(default='dfd', on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('subCategory', models.ForeignKey(default='ffsf', on_delete=django.db.models.deletion.DO_NOTHING, to='api.subcategory')),
            ],
        ),
    ]
