# Generated by Django 4.0.4 on 2024-05-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='cust_id',
            new_name='cust',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='prod_id',
            new_name='prod',
        ),
    ]
