# Generated by Django 4.0.4 on 2022-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
