# Generated by Django 4.0.4 on 2024-05-22 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cust_id_feedback_cust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
