# Generated by Django 4.0.4 on 2024-04-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default='0')),
                ('comment', models.CharField(max_length=100)),
                ('cust_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('prod_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
        ),
    ]
