# Generated by Django 4.0.4 on 2024-05-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cart_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
