# Generated by Django 4.0.4 on 2024-05-23 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='add',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='api.address'),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='color',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='paymentMode',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='price',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='address',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
