# Generated by Django 4.0.4 on 2024-05-01 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_address_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='cust_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='products',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='cust_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
