# Generated by Django 4.0.4 on 2024-05-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordersummary_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='transaction_id',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
