# Generated by Django 4.0.4 on 2024-05-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ordersummary_cust_id_ordersummary_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='cust_id',
        ),
    ]
