# Generated by Django 4.0.4 on 2024-05-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ordersummary_color_remove_ordersummary_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='add',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='cust',
            field=models.CharField(max_length=20),
        ),
    ]
