# Generated by Django 4.0.4 on 2024-05-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ordersummary_add_alter_ordersummary_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='prod',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
