# Generated by Django 4.0.4 on 2024-05-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_ordersummary_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='paymentMode',
            field=models.CharField(max_length=20),
        ),
    ]
