# Generated by Django 4.0.4 on 2024-05-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_ordersummary_paymentmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='transit_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='Ordered', max_length=20),
        ),
    ]
