# Generated by Django 4.0.4 on 2024-05-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ordersummary_transit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='transit_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Ordered', max_length=20),
        ),
    ]
