# Generated by Django 4.0.4 on 2024-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_ordersummary_transit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stockCount',
            field=models.CharField(default='5', max_length=20),
        ),
    ]
