# Generated by Django 4.0.4 on 2024-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cart_stockcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='stockCount',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
