# Generated by Django 4.0.4 on 2024-05-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_cart_stockcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='stockCount',
        ),
    ]
