# Generated by Django 4.0.4 on 2024-05-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_cart_stockcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
