# Generated by Django 4.0.4 on 2024-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_cart_image_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cust',
            field=models.CharField(max_length=100),
        ),
    ]
