# Generated by Django 4.0.4 on 2024-05-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_feedback_prod_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='no_img.jpg', upload_to='images/subCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_img.jpg', upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='no_img.jpg', upload_to='images/subCategory'),
        ),
    ]
