# Generated by Django 4.0.4 on 2024-05-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prod',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
