# Generated by Django 4.0.4 on 2024-05-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_cart_prod_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
