# Generated by Django 4.0.4 on 2024-05-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_ordersummary_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded')], default='pending', max_length=100),
        ),
    ]
